[package]
name = "habitat_http_client"
version = "0.0.0"
edition = "2018"
authors = ["The Habitat Maintainers <humans@habitat.sh>"]
build = "build.rs"
workspace = "../../"

[dependencies]
base64 = "*"
log = "*"
httparse = "*"
hyper = "0.10"
hyper-openssl = "0.2"
# JB: pinning this for now to avoid a ton of breaking changes
openssl = "0.9.23"
serde = "*"
serde_json = "*"
url = "*"

[dependencies.habitat_core]
path = "../core"

[features]
default = []
functional = []
