[package]
name = "habitat_win_users"
version = "0.0.0"
edition = "2018"
authors = ["Matt Wrock <matt@mattwrock.com>"]
description = "Habitat library for win32 account api calls"
workspace = "../../"
build = "build.rs"

[build-dependencies]
gcc = "0.3"

[dependencies]
log = "*"

[target.'cfg(windows)'.dependencies]
widestring = "*"
winapi = { version = "*", features = ["winbase", "winerror", "handleapi"] }
