[package]
name = "habitat_win_users"
version = "0.0.0"
edition = "2018"
authors = ["The Habitat Maintainers <humans@habitat.sh>"]
description = "Habitat library for win32 account api calls"
workspace = "../../"
build = "build.rs"

[build-dependencies]
gcc = "0.3"

[dependencies]
log = "*"

[target.'cfg(windows)'.dependencies]
# Moving to 0.4.0 is breaking some of our windows API calls
# pinning to 0.3.0 until we can get to the bottom of those
# breakages. See https://github.com/habitat-sh/core/issues/127
widestring = "0.3.0"
winapi = { version = "*", features = ["winbase", "winerror", "handleapi"] }
